# Generated by Django 3.2.19 on 2023-06-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='边编号')),
                ('distance', models.DecimalField(decimal_places=5, max_digits=7, null=True, verbose_name='边长度')),
            ],
            options={
                'db_table': 'edges',
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='线路编号')),
                ('name', models.CharField(max_length=100, verbose_name='线路名称')),
            ],
            options={
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='管理员账号')),
                ('password', models.CharField(max_length=30, verbose_name='管理员密码')),
            ],
            options={
                'db_table': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='站点编号')),
                ('name', models.CharField(max_length=40, verbose_name='站点名称')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='站点经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='站点经度')),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='LineStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(db_column='line_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.lines')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.stations')),
            ],
            options={
                'db_table': 'line_station',
            },
        ),
        migrations.AddField(
            model_name='lines',
            name='startStation',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.stations'),
        ),
        migrations.CreateModel(
            name='LineEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge', models.ForeignKey(db_column='edge_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.edges')),
                ('line', models.ForeignKey(db_column='line_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.lines')),
            ],
            options={
                'db_table': 'line_edge',
            },
        ),
        migrations.CreateModel(
            name='EdgeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge', models.ForeignKey(db_column='edge_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.edges')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.stations')),
            ],
            options={
                'db_table': 'edge_station',
            },
        ),
    ]
